### PR TITLE
Feature/issue 176/add refactor token management

### PR DESCRIPTION
**Pull request by KhalilGarali**
Linked Issue: #176 

#### Description / Things done in this PR:
- Switched from AsyncStorage to expo secure store. More secure, better performance.
- Updated/refactored axiosInstance to align with expo secure store and fix a bug where we would always get 401 if there was an error.
- Added test cases. More substantial test cases should be added for axios instance later on.
- Refactored the code to be more exception oriented, rather than focusing on if statements.

### CODE REVIEW

**Review by yousfino — DISMISSED** [review]
looks good to me!

**Review by NicolasChelico — DISMISSED** [review]
I know im repeating myself but we must remember to remove the console.log conatining the refresh tokens and other sensitive info. Besides that, fantastic work

**Comment by KhalilGarali** [comment]
> I know im repeating myself but we must remember to remove the console.log conatining the refresh tokens and other sensitive info. Besides that, fantastic work

Yes, of course I agree with you too. All the consoles.log will be taken out once I finish my next task/issue. That way I know everything is set up correctly.

**Review by JRB958 — APPROVED** [review]
LGTM! well done

**Review by NicolasChelico — APPROVED** [review]

**Pull request merged**
