### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by KhalilGarali**
New issue template for opening bugs

### CODE REVIEW

**Review by walidoow — APPROVED** [review]

**Comment by walidoow** [comment]
@KhalilGarali before merging can you make a ticket for it, and rename your last commit following our commit convention (using the ticket number)? 

To rename your last commit, follow this:
1. Type the command `git commit --amend`
2. Type `i` and the using your arrows move around the file to rename your commit
3. Type `esc`
4. Type `:` followed by `wq` and then type `Enter`
5. Lasty, push with `git push --force-with-lease`

**Review by walidoow — CHANGES_REQUESTED** [review]
@KhalilGarali before merging can you make a ticket for it, and rename your last commit following our commit convention (using the ticket number)? 

To rename your last commit, follow this:
1. Type the command `git commit --amend`
2. Type `i` and the using your arrows move around the file to rename your commit
3. Type `esc`
4. Type `:` followed by `wq` and then type `Enter`
5. Lasty, push with `git push --force-with-lease`

**Comment by KhalilGarali** [comment]
> @KhalilGarali before merging can you make a ticket for it, and rename your last commit following our commit convention (using the ticket number)?
> 
> To rename your last commit, follow this:
> 
> 1. Type the command `git commit --amend`
> 2. Type `i` and the using your arrows move around the file to rename your commit
> 3. Type `esc`
> 4. Type `:` followed by `wq` and then type `Enter`
> 5. Lasty, push with `git push --force-with-lease`

Renamed the last commit, no need for another ticket since this is already linked.

**Review by walidoow — APPROVED** [review]
lgtm!

**Pull request merged**
