### PR TITLE
GH-77: [feat] Add update for events

### PR DESCRIPTION
**Pull request by Ziadsharkos**
# Implement PUT and PATCH Methods to Update Event Model in Event-Service  

## Description  

This PR introduces two new endpoints in the `event-service` to enable updating event details:  

- **PUT (`/events/{eventId}`):** Allows a full replacement of an event's details.  
- **PATCH (`/events/{eventId}`):** Enables partial updates to specific fields of an event.  

Both endpoints include validation, authentication, and authorization mechanisms to ensure data integrity and security. Comprehensive unit and integration tests were written to verify correctness and edge cases. Swagger documentation was updated to provide clear usage instructions for developers.  

---

### 1. PUT Endpoint (`/events/{eventId}`)  

- **Purpose:** Fully replace the existing event object with the data provided in the request body.  
- **Implementation Details:**  
  - Added the `putEvent` method in `EventController`.  
  - Developed service-layer logic to:  
    - Validate the input.  
    - Check event existence.  
    - Overwrite all fields in the event object.  
  - Ensured that only authenticated users can perform this action.  

### 2. PATCH Endpoint (`/events/{eventId}`)  

- **Purpose:** Allow partial updates to specific fields of an event while retaining unmodified data.  
- **Implementation Details:**  
  - Added the `patchEvent` method in `EventController`.  
  - Implemented logic in the service layer to:  
    - Validate the provided fields.  
    - Check event existence.  
    - Apply only the changes from the request, leaving other fields intact.  
  - Ensured that only authenticated users can perform this action.  

### 3. Validation and Authorization  

- Input validation added to prevent invalid or malicious updates.  
- Authentication enforced to allow only authorized users to update events.  
- Checked for event existence before attempting updates, with appropriate error responses.  

### 4. Testing  

- **Unit Tests:**  
  - Covered edge cases and behavior of `putEvent` and `patchEvent` methods.  
  - Validated repository interactions using mocks.  
- **Integration Tests:**  
  - Verified end-to-end functionality of PUT and PATCH endpoints, including:  
    - Request/response validation.  
    - Persistence behavior.  

---

## Files Modified/Added  

1. **Controller:**  
   - `EventController`: Added `putEvent` and `patchEvent` methods.  

2. **Service:**  
   - `EventService`: Added `putEvent` and `patchEvent` methods.  

3. **Models:**  
   - Enhanced request models for differentiation between full and partial updates.  

4. **Repository:**  
   - Leveraged existing repository methods for data persistence.  

5. **Testing:**  
   - `EventServiceTest`: Added unit tests for service methods.  
   - `EventControllerIntegrationTest`: Added integration tests for endpoint behavior.

### CODE REVIEW

**Review by walidoow — APPROVED** [review]
Looks good to me

**Comment by wolfie7679** [comment]
This may be a bit late, but I think it would be a good idea to add some javadoc for both endpoints, as put and patch may be confusing down the line

**Comment by walidoow** [comment]
> This may be a bit late, but I think it would be a good idea to add some Javadoc for both endpoints, as put and patch may be confusing down the line

Maybe using the `@Operation` for Swagger docs is enough?

Like this as an example: https://github.com/SOEN490-SportsApp/SportsApp/blob/49ac4a6cc25075fda07301a780ce51d10b3f5490/Microservices/user-service/src/main/java/app/sportahub/userservice/controller/user/UserController.java#L28C1-L29C72

Since we have to provide the Swagger docs, adding javadocs would be too redundant, we have to `keep it DRY`. We should leave the Javadocs for implementation-specific stuff or for internal documentation.

Since the `PUT` and `PATCH` are basic CRUD operations, I believe the Javadocs would be too overkill for the operations. The Swagger for the API-level documentation should be enough. The endpoints in the controller are very simple, they are just calling the service in one line. I do agree that maybe the methods in the services need Javadocs.

- @Ziadsharkos you can try to just mention in the Swagger what every operation does in the description using `@Operation`.

What do you think @wolfie7679?

**Comment by Ziadsharkos** [comment]
> This may be a bit late, but I think it would be a good idea to add some javadoc for both endpoints, as put and patch may be confusing down the line

Thanks for pointing it out, it has been added.

**Review by wolfie7679 — APPROVED** [review]
fantastic!

**Pull request merged**
